system:
  type: ADMIN

# 配置文件加密key 生产环境中可通过环境变量、命令行等形式进行设置
jasypt:
  encryptor:
    password: admin

server:
  port: 9090
  servlet:
    context-path: /admin
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30

logging:
  config: classpath:log4j2.xml

mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  global-config:
    banner: false
#    db-config:
#      id-type: auto
  type-enums-package: com.small.admin.enums
  type-aliases-package: com.small.admin.entity.po,com.small.admin.entity.dto

spring:
  # 数据源
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/scuser?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Lhl-123456
    # Jasypt加密 可到common-utils中找到JasyptUtil加解密工具类生成加密结果 格式为ENC(加密结果) 以下解密结果为123456
#    password: ENC(F4B0s6u9xcDw3V+P0qC4CA==)

    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    # Druid StatViewServlet配置
    druid:
      stat-view-servlet:
        # 默认true 内置监控页面首页/druid/index.html
        enabled: true
        url-pattern: /druid/*
        # 允许清空统计数据
        reset-enable: true
        login-username: root
#        login-password: ENC(F4B0s6u9xcDw3V+P0qC4CA==)
        login-password: 123456
        # IP白名单 多个逗号分隔
        allow:
        # IP黑名单
        deny:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non-null
    serialization:
      fail-on-empty-beans: false
  redis:
    #数据库索引
    database: 0
    host: 127.0.0.1
    port: 6379
#    password: root
    lettuce:
      pool:
        #最大连接数
        max-active: 8
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        #最大空闲
        max-idle: 8
        #最小空闲
        min-idle: 0
        #连接超时时间
        timeout: 10000

#  # 定时任务
#  quartz:
#    # 任务信息存储至数据库
#    job-store-type: jdbc
#    properties:
#      org:
#        quartz:
#          jobStore:
#            misfireThreshold: 100


small:
  # 全局限流
  ratelimit:
    enable: true
    # 每1秒内
    timeout: 1000
    # 总限制100个请求
    limit: 100
  # IP限流
  iplimit:
    enable: true
    # 每1秒内
    timeout: 1000
    # 每个ip限制15个请求
    limit: 15
  # token交互方式
  token:
    # 设置为true后，token将存入redis，并具有单点登录功能 默认false使用JWT交互
    redis: true
    # 是否开启单设备登陆 仅当token交互方式为redis时生效
    sdl: true
    # token中存储用户权限数据 设为true开启后可避免每次请求再获取用户权限，但有可能导致编辑权限菜单后无法读取到最新权限数据（需用户重新登录）
    storePerms: true
    # token过期时间（分钟）
    tokenExpireTime: 60
    # 用户选择保存登录状态对应token过期时间（天）
    saveLoginTime: 7
    # 限制用户登陆错误次数（次）
    loginTimeLimit: 10
    # 错误超过次数后多少分钟后才能继续登录（分钟）
    loginAfterTime: 10
  # 日志记录方式 true使用Elasticsearch记录 false记录至数据库中
#  logRecord:
#    es: false

## 需要验证码校验的接口路径 支持通配符 自动过滤拦截校验 无需开发人员再次校验
#captcha:
#  # 图片验证码验证
#  image:
#    - /admin/login # 登录接口

# 忽略鉴权url
ignored:
  urls:
    - /admin/actuator/**
    - /admin/common/**
    - /druid/**
    - /swagger-ui.html
    - /swagger-resources/**
    - /swagger/**
    - /**/v2/api-docs
    - /**/*.js
    - /**/*.css
    - /**/*.png
    - /**/*.ico
    - /test/**
    - /login.html

# Actuator
management:
  health:
    status:
      http-mapping:
        DOWN: 200
        OUT_OF_SERVICE: 200
        FATAL: 200
        UNKNOWN: 200
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /admin/actuator/
      exposure:
        include: '*'

# Swagger界面内容配置
swagger:
  title: admin API接口文档
  description: admin Api Documentation
  version: 1.0.0
  termsOfServiceUrl: https://blog.csdn.net/allen_lu_hh
  contact:
    name: admin
    url: http://funnylu.top/
    email: allen_lu_hh@163.com